name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          sudo apt-get install -y zip unzip autoconf libtool pkg-config zlib1g-dev openjdk-17-jdk
          sudo apt-get install -y cmake libncurses5-dev libncursesw5-dev libtinfo5 python3-setuptools python3-distutils python3.10-venv
          pip install --upgrade "cython<3.0.0" buildozer virtualenv setuptools wheel

      - name: Allow Action
        run: sudo chmod -R 777 .

      - name: Build with Buildozer
        run: |
          sudo apt install -y xvfb
          yes | xvfb-run -a buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
